---
name: CI

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*.*.*
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: fish {0}

    steps:
      - uses: actions/checkout@v2

      - uses: fish-actions/install-fish@v1

      - name: Install Fisher
        run: curl -sL git.io/fisher | source && fisher install jorgebucaran/fisher

      - name: Install Tide
        run: fisher install $GITHUB_WORKSPACE

      - name: Install testing dependencies
        run: tide test --install

      - name: Run full test suite
        run: tide test --all --CI
