---
name: docs

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v*.*.*
    paths:
      - "**.md"
      - "**.yml"
  pull_request:
    paths:
      - "**.md"
      - "**.yml"

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actionsx/prettier@v2
        with:
          args: --check .

  super-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MD: true
          VALIDATE_YAML: true
